# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Web Publishing with Jekyll & GitHub Pages
email: menzenski@ku.edu
description: > # this means to ignore newlines until "baseurl:"
  This is a companion site to the March 3rd workshop "Easy & Sustainable
  Web Publishing with Plain Text, Jekyll & GitHub", offered as a Digital
  Jumpstart workshop by the University of Kansas Institute for Digital
  Research in the Humanities.
baseurl: "/idrh-static-site-workshop" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: menzenski
github_username: menzenski

# Build settings
markdown: kramdown
permalink: /:year/:month/:day/:slug/
